/**
 * Enterprise Evidence Manager
 *
 * Records, indexes and retrieves forensic evidence generated by the analytics platform.
 *
 * Evidence links to alarms and contains:
 *   - AI metadata (model version, confidence, bounding boxes, track ID)
 *   - Camera and timestamp
 *   - Snapshot and video clip references (set when recording pipeline clips footage)
 *
 * NEVER stores synthetic or simulated evidence.
 * Every EvidenceRecord must originate from a real AI or sensor detection event.
 */

import { db } from './firestoreService';
import { collection, addDoc, getDocs, query, where, orderBy, limit } from 'firebase/firestore';
import type { BoundingBox } from './ai/interfaces';

export interface EvidenceRecord {
  id            : string;
  alarmId      ?: string;
  eventType     : string;           // e.g. 'FIRE_DETECTED', 'PPE_VIOLATION'
  cameraId      : string;
  timestamp     : string;           // ISO-8601
  confidence    : number;           // [0.0, 1.0]
  aiModelVersion: string;
  boundingBoxes?: BoundingBox[];
  trackId      ?: string;
  location     ?: string;
  snapshotRef  ?: string;           // Storage path or URL for a frame snapshot
  videoClipRef ?: string;           // Storage path or URL for a short clip
  metadata      : Record<string, any>;
}

class EvidenceManager {
  private static instance: EvidenceManager;
  private store: Map<string, EvidenceRecord> = new Map();
  private counter = 0;

  private constructor() {}

  public static getInstance(): EvidenceManager {
    if (!EvidenceManager.instance) {
      EvidenceManager.instance = new EvidenceManager();
    }
    return EvidenceManager.instance;
  }

  /**
   * Record a new evidence item and persist to Firestore.
   * Returns the created EvidenceRecord with its assigned ID.
   */
  public record(params: {
    alarmId      ?: string;
    eventType     : string;
    cameraId      : string;
    timestamp    ?: string;
    confidence    : number;
    aiModelVersion?: string;
    boundingBoxes?: BoundingBox[];
    trackId      ?: string;
    location     ?: string;
    snapshotRef  ?: string;
    videoClipRef ?: string;
    metadata     ?: Record<string, any>;
  }): EvidenceRecord {
    this.counter++;
    const id = `EVD-${Date.now()}-${String(this.counter).padStart(4, '0')}`;

    const evidence: EvidenceRecord = {
      id,
      alarmId       : params.alarmId,
      eventType     : params.eventType,
      cameraId      : params.cameraId,
      timestamp     : params.timestamp ?? new Date().toISOString(),
      confidence    : params.confidence,
      aiModelVersion: params.aiModelVersion ?? 'sentinel-analytics-1.0',
      boundingBoxes : params.boundingBoxes,
      trackId       : params.trackId,
      location      : params.location,
      snapshotRef   : params.snapshotRef,
      videoClipRef  : params.videoClipRef,
      metadata      : params.metadata ?? {},
    };

    this.store.set(id, evidence);
    this.persistToFirestore(evidence).catch(() => {});
    return evidence;
  }

  /** Attach a snapshot or clip reference to an existing evidence record. */
  public attachMedia(
    evidenceId  : string,
    snapshotRef?: string,
    videoRef   ?: string,
  ): boolean {
    const ev = this.store.get(evidenceId);
    if (!ev) return false;
    if (snapshotRef) ev.snapshotRef = snapshotRef;
    if (videoRef)    ev.videoClipRef = videoRef;
    this.persistToFirestore(ev).catch(() => {});
    return true;
  }

  public get(id: string): EvidenceRecord | undefined {
    return this.store.get(id);
  }

  public forAlarm(alarmId: string): EvidenceRecord[] {
    return Array.from(this.store.values())
      .filter(e => e.alarmId === alarmId)
      .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
  }

  public search(filters?: {
    cameraId ?: string;
    eventType?: string;
    since    ?: string;   // ISO date string
    limit    ?: number;
  }): EvidenceRecord[] {
    let results = Array.from(this.store.values());
    if (filters?.cameraId)  results = results.filter(e => e.cameraId  === filters.cameraId);
    if (filters?.eventType) results = results.filter(e => e.eventType === filters.eventType);
    if (filters?.since) {
      const sinceMs = new Date(filters.since).getTime();
      results = results.filter(e => new Date(e.timestamp).getTime() >= sinceMs);
    }
    results.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    if (filters?.limit) results = results.slice(0, filters.limit);
    return results;
  }

  public count(cameraId?: string): number {
    if (!cameraId) return this.store.size;
    let n = 0;
    for (const e of this.store.values()) if (e.cameraId === cameraId) n++;
    return n;
  }

  private async persistToFirestore(ev: EvidenceRecord): Promise<void> {
    try {
      await addDoc(collection(db, 'analyticsEvidence'), JSON.parse(JSON.stringify(ev)));
    } catch {
      // Non-blocking
    }
  }
}

export const evidenceManager = EvidenceManager.getInstance();
