
import React, { useState, useEffect } from 'react';
import { logService } from '../services/logService';
import { AttendanceRecord, AttendanceStatus } from '../types';
import { ShieldCheck, ShieldAlert, Sparkles, RefreshCw, Search, User as UserIcon, Clock, CheckCircle2, AlertTriangle, X } from 'lucide-react';
import { analyzeSecurityLogs, SecurityAuditReport } from '../services/geminiService';
import { useLanguage } from '../services/i18n';

export const AttendanceLogViewer: React.FC<{ globalSearchTerm?: string }> = ({ globalSearchTerm }) => {
  const [logs, setLogs] = useState<AttendanceRecord[]>([]);
  const [aiAnalysis, setAiAnalysis] = useState<SecurityAuditReport | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const { language } = useLanguage();

  useEffect(() => {
    const loadLogs = async () => {
        const data = await logService.getAttendanceLogs();
        setLogs(data);
    };
    loadLogs();
  }, []);

  const filteredLogs = logs.filter(log => 
    !globalSearchTerm || 
    log.userName.toLowerCase().includes(globalSearchTerm.toLowerCase()) ||
    log.id.toLowerCase().includes(globalSearchTerm.toLowerCase()) ||
    log.department.toLowerCase().includes(globalSearchTerm.toLowerCase())
  );

  const handleAiAudit = async () => {
    setIsAnalyzing(true);
    // Analyze only the currently visible/filtered logs
    const result = await analyzeSecurityLogs(filteredLogs, language);
    setAiAnalysis(result);
    setIsAnalyzing(false);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white">Access Logs</h2>
          <p className="text-slate-400">Real-time biometric transaction history</p>
        </div>
        <button
          onClick={handleAiAudit}
          disabled={isAnalyzing}
          className="flex items-center justify-center space-x-2 bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2.5 rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-indigo-900/20"
        >
          {isAnalyzing ? (
            <RefreshCw className="w-5 h-5 animate-spin" />
          ) : (
            <Sparkles className="w-5 h-5" />
          )}
          <span>{isAnalyzing ? 'Analyzing...' : 'Run AI Security Audit'}</span>
        </button>
      </div>

      {/* AI Analysis Result Section */}
      {aiAnalysis && (
        <div className="bg-slate-900 border border-indigo-500/30 p-6 rounded-xl animate-in slide-in-from-top-4 duration-500 relative overflow-hidden shadow-2xl">
            <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none">
                <Sparkles className="w-64 h-64 text-indigo-400" />
            </div>
            
            <div className="relative z-10">
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-indigo-500/20 rounded-lg border border-indigo-500/30">
                            <Sparkles className="w-6 h-6 text-indigo-400" />
                        </div>
                        <div>
                            <h3 className="text-white font-bold text-lg">AI Security Audit Report</h3>
                            <p className="text-slate-400 text-xs">Generated by Gemini 3 Flash • Based on {filteredLogs.length} Records</p>
                        </div>
                    </div>
                    <button 
                        onClick={() => setAiAnalysis(null)} 
                        className="text-slate-500 hover:text-white transition-colors"
                        title="Close Report"
                    >
                        <X size={20} />
                    </button>
                </div>

                <div className="space-y-6">
                    <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
                        <p className="text-slate-300 text-sm leading-relaxed italic">"{aiAnalysis.summary}"</p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        {/* Anomalies */}
                        <div className="bg-red-950/10 border border-red-500/20 p-4 rounded-xl hover:bg-red-950/20 transition-colors">
                            <h4 className="text-red-400 font-bold text-xs uppercase tracking-widest mb-3 flex items-center gap-2">
                                <AlertTriangle size={14} /> Anomalies Detected
                            </h4>
                            <ul className="space-y-3">
                                {aiAnalysis.anomalies.length > 0 ? aiAnalysis.anomalies.map((item, i) => (
                                    <li key={i} className="text-xs text-red-200/80 flex items-start gap-2">
                                        <span className="mt-1.5 w-1.5 h-1.5 bg-red-500 rounded-full shrink-0"></span>
                                        <div>
                                            <strong className="text-red-300 block mb-0.5">{item.type}</strong>
                                            <span className="text-red-200/70">{item.description}</span>
                                        </div>
                                    </li>
                                )) : <li className="text-xs text-slate-500 italic">No anomalies detected. System secure.</li>}
                            </ul>
                        </div>

                        {/* Patterns */}
                        <div className="bg-blue-950/10 border border-blue-500/20 p-4 rounded-xl hover:bg-blue-950/20 transition-colors">
                            <h4 className="text-blue-400 font-bold text-xs uppercase tracking-widest mb-3 flex items-center gap-2">
                                <Clock size={14} /> Attendance Patterns
                            </h4>
                            <ul className="space-y-2">
                                {aiAnalysis.patterns.length > 0 ? aiAnalysis.patterns.map((item, i) => (
                                    <li key={i} className="text-xs text-blue-200/80 flex items-start gap-2">
                                        <span className="mt-1.5 w-1 h-1 bg-blue-500 rounded-full shrink-0"></span>
                                        {item}
                                    </li>
                                )) : <li className="text-xs text-slate-500 italic">No significant patterns identified.</li>}
                            </ul>
                        </div>

                        {/* Recommendations */}
                        <div className="bg-emerald-950/10 border border-emerald-500/20 p-4 rounded-xl hover:bg-emerald-950/20 transition-colors">
                            <h4 className="text-emerald-400 font-bold text-xs uppercase tracking-widest mb-3 flex items-center gap-2">
                                <CheckCircle2 size={14} /> Recommendations
                            </h4>
                            <ul className="space-y-2">
                                {aiAnalysis.recommendations.length > 0 ? aiAnalysis.recommendations.map((item, i) => (
                                    <li key={i} className="text-xs text-emerald-200/80 flex items-start gap-2">
                                        <span className="mt-1.5 w-1 h-1 bg-emerald-500 rounded-full shrink-0"></span>
                                        {item}
                                    </li>
                                )) : <li className="text-xs text-slate-500 italic">No operational actions required.</li>}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      )}

      <div className="bg-slate-900 shadow-xl rounded-xl border border-slate-800 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="bg-slate-950 border-b border-slate-800">
              <tr>
                <th className="px-6 py-4 font-semibold text-slate-400 uppercase text-xs tracking-wider">Timestamp</th>
                <th className="px-6 py-4 font-semibold text-slate-400 uppercase text-xs tracking-wider">User / Identity</th>
                <th className="px-6 py-4 font-semibold text-slate-400 uppercase text-xs tracking-wider">Status</th>
                <th className="px-6 py-4 font-semibold text-slate-400 uppercase text-xs tracking-wider">Confidence</th>
                <th className="px-6 py-4 font-semibold text-slate-400 uppercase text-xs tracking-wider">Liveness</th>
                <th className="px-6 py-4 font-semibold text-slate-400 uppercase text-xs tracking-wider">Node ID</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800">
              {filteredLogs.length > 0 ? filteredLogs.map((log) => (
                <tr key={log.id} className="hover:bg-slate-800/50 transition-colors">
                  <td className="px-6 py-4 text-slate-400 font-mono text-xs">{log.timestamp}</td>
                  <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        {log.userAvatar ? (
                             <img src={log.userAvatar} className="w-8 h-8 rounded-full bg-slate-800 object-cover border border-slate-700" alt="" />
                        ) : (
                             <div className="w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center text-slate-500 border border-slate-700">
                                <UserIcon size={14}/>
                             </div>
                        )}
                        <div>
                            <p className="font-bold text-slate-200">{log.userName}</p>
                            <p className="text-xs text-slate-500">{log.department}</p>
                        </div>
                      </div>
                  </td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex items-center px-2.5 py-1 rounded-md text-xs font-bold border ${
                      log.status === AttendanceStatus.PRESENT ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                      log.status === AttendanceStatus.LATE ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' :
                      'bg-rose-500/10 text-rose-400 border-rose-500/20'
                    }`}>
                      {log.status}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                        <div className="w-16 h-1.5 bg-slate-800 rounded-full overflow-hidden">
                            <div 
                                className={`h-full rounded-full ${log.confidenceScore > 0.9 ? 'bg-emerald-500' : log.confidenceScore > 0.7 ? 'bg-amber-500' : 'bg-rose-500'}`} 
                                style={{ width: `${log.confidenceScore * 100}%` }} 
                            />
                        </div>
                        <span className="text-xs text-slate-400 font-mono">{(log.confidenceScore * 100).toFixed(0)}%</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    {log.livenessVerified ? (
                      <div className="flex items-center text-emerald-400 gap-1.5" title="Passive Liveness Passed">
                        <ShieldCheck className="w-4 h-4" />
                        <span className="text-xs font-medium">Verified</span>
                      </div>
                    ) : (
                      <div className="flex items-center text-rose-400 gap-1.5" title="Liveness Check Failed">
                        <ShieldAlert className="w-4 h-4" />
                        <span className="text-xs font-medium">Failed</span>
                      </div>
                    )}
                  </td>
                  <td className="px-6 py-4 text-slate-500 text-xs font-mono">{log.nodeId}</td>
                </tr>
              )) : (
                <tr>
                    <td colSpan={6} className="px-6 py-12 text-center text-slate-500">
                        <div className="flex flex-col items-center justify-center gap-2">
                            <Search size={24} className="opacity-20" />
                            <p>No logs found matching "{globalSearchTerm}".</p>
                        </div>
                    </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
