apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentinel-vms.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel-vms.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.nodeEnv | default "production" | quote }}
  PORT: {{ .Values.service.targetPort | default 5000 | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | default "info" | quote }}
  METRICS_PORT: {{ .Values.service.metricsPort | default 9090 | quote }}
  {{- with .Values.env.extraEnv }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
